apiVersion: apps/v1
kind: Deployment
metadata:
  name: workon
  namespace: workon
spec:
  selector:
    matchLabels:
      app: workon
  replicas: 2
  template:
    metadata:
      labels:
        app: workon
    spec:
      containers:
      - name: workon
        image: rfahham/workon:1.0.0
        ports:
        - containerPort: 80