name: CI-CD

on:
  push:
    branches: [ "main" ]
    paths-ignore: 
      - ./k8s/*
  pull_request:
    branches: [ "main" ]
    paths-ignore: 
      - ./k8s/*
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código fonte 
        uses: actions/checkout@v4.1.7

      - name: Login no Docker HUB
        uses: docker/login-action@v3.2.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Construção da imagem
        uses: docker/build-push-action@v6.2.0
        with:
          context: .
          push: true
          file: Dockerfile
          tags: |
            rfahham/workon:v${{ github.run_number}}
            rfahham/workon:latest
  
  CD:
    runs-on: ubuntu-latest
    needs: [CI]

    steps:
    - name: Obtendo o código
      uses: actions/checkout@v4
    
    - name: Gitops --Patch and push
      run: |
        git config --global user.name "rfahham"
        git config --global user.email "rfahham@hotmail.com"
        sed -i 's/image: rfahham/workon:v[0-9]\{1,3\}/image: rfahham\/workon:v${{github.run_number}}/' ./k8s/deployment.yaml
        git add ./k8s
        git commit -m "Alteração para a imagem rfahham/workon:v${{ github.run_number}}"
        git push origin